JS Week2 Homework
negaren/hyf-homework pull request #3
Opened 2021-11-05 12:59 UTC by negaren

2021-11-05 13:00 UTC, negaren commented
JS1 Week2 Homework

2021-11-06 09:49 UTC, aina21 requested changes
good job :+1:

2021-11-06 09:49 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +let fullname1 = getFullname2("Negar", "Namini", true);
you're not changing fullname1 value, so change it to const. always use const first, until it doesn't let you.

2021-11-06 09:49 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +let fullname2 = getFullname2("Negar", "Namini");
const

2021-11-06 09:49 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +    const toDayNumber = today.getDay();
everywhere you are using toDayNumber with decrease one. so you can do it here l mean
const toDayNumber = today.getDay() -1;

2021-11-06 09:49 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +        console.log("Today is " + '"', weekDays[toDayNumber - 1], '"' + " and the event day is on:" + '"', weekDays[toDayNumber + dayNumber - 1], '"');
this solution doesn't work properly if the value of `toDayNumber + dayNumber - 1` be more than 6 (size of array). fx  toDayNumber = 6, dayNumber= 2

2021-11-06 09:49 UTC, aina21 commented on javascript/javascript1/week2/index.js
> +        console.log("Today is " + '"', weekDays[toDayNumber - 1], '"' + " and the event day is on: " + '"', weekDays[(dayNumber % 7) + toDayNumber - 1], '"');
same toDayNumber = 6, dayNumber= 9

you can find a right index like this (dayNumber+toDayNumber)%7

2021-12-02 19:27 UTC, merged