JS1 Week3 Homework version1
negaren/hyf-homework pull request #4
Opened 2021-11-11 22:16 UTC by negaren

Version 1 of JS1 week3 homework

2021-11-13 20:58 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +var notes = [];
avoid using var, use const instead

2021-11-13 21:00 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +            return notes[i].content;
I think, it only works if call function with id=1, because you return inside a loop.

2021-11-13 21:01 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +let firstNote = getNote(1);
const

2021-11-13 21:02 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +let activities = [];
you can use const

2021-11-13 21:03 UTC, aina21 commented on javascript/javascript1/week3/index.js
> +var todayDate = new Date();
avoid var

2021-11-13 21:03 UTC, aina21 requested changes
nice job :+1:

2021-11-22 17:22 UTC, negaren commented on javascript/javascript1/week3/index.js
> +var todayDate = new Date();
Done

2021-11-22 17:23 UTC, merged